package com.example;


import com.example.domain.sort.ArrayInput;
import com.example.domain.sort.BubbleSort;
import com.example.domain.sort.InsertionSort;
import com.example.domain.sort.SelectionSort;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.PropertySource;
import org.springframework.context.annotation.PropertySources;
import org.springframework.core.env.Environment;

import java.time.LocalDateTime;

@SpringBootApplication
@PropertySources ( {
 @PropertySource ("classpath:application.properties") /* git.properties file will be generated by the plugin*/
})

public class DataStructuresApplication {
	// Main driver method
	public static void main (String[] args) {

		ConfigurableApplicationContext applicationContext = SpringApplication.run(DataStructuresApplication.class, args);
		Environment environment = applicationContext.getEnvironment();

		String javaVersion = Runtime.version().toString();
		String time = LocalDateTime.now().toString();
		System.out.println("********\nBuild Time: " + time
		 + "\nJava Version: " + javaVersion + "\n********");


		ArrayInput arrayInput = new ArrayInput();
		int a[] = arrayInput.takeArrayInput();

		BubbleSort bubbleSort = new BubbleSort();
		bubbleSort.bubbleSort(a);
		InsertionSort insertionSort = new InsertionSort();
		insertionSort.insertionSort(a);
		SelectionSort selectionSort = new SelectionSort();
		selectionSort.selectionSort(a);


	}


}
